### ISSUE TITLE
AMQP 1.0

### ISSUE THREAD

**Issue by vog** [andersfugmann/amqp-client#17]
Are there any plans to support the AMQP 1.0 standard?

**Comment by andersfugmann** [comment]
Not at the moment, and I doubt this library ever will.
Amqp spec 1.0 is not a simple update to  the 0.9.1 protocol but rather a completely new protocol. 

The protocol does not mention queues, exchanges or bindings so it would be hard to make an generic implementation that does more that just implement the wire format. I even doubt that there would be much  code reuse.

Do you have any concrete use case for using Amqp 1.0 spec over the 0.9.1? Which broker are you using?

**Comment by vog** [comment]
AMQP 1.0 is used at some places in the aviation domain, and most likely other industries, where AMQP < 1.0 is not used at all.

There are some Java implementations, such as ActiveMQ. There also even C/C++ implementations, which one could wrap. But I thought a pure OCaml implementation would be preferrable.

**Comment by andersfugmann** [comment]
The problem with the AMQP protocol 1.0 it is only a protocol specification and high level API needs to be matched the broker used (if a broker is used at all).  The design goal of this library was(is) to provide high level bindings to AMQP version 0.9.1 as the 0.9.1 specifies semantics in addition to the wire protocol. 

If the C implementation supports constructing messages in memory it should be relatively easy to use with ctypes and then have ocaml handle all the communication.
