### ISSUE TITLE
Fails to build on OPAM 2.0~rc2

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [andersfugmann/amqp-client#18]
OPAM 2 introduced sandboxing in version rc2, so the build fails in the step where `curl` retrieves the spec of AMQP: `curl: (6) Could not resolve host: www.rabbitmq.com`.

I think it would be nice if the package did not depend on the reachability of the RabbitMQ home page and would just inline this file. This would also avoid the implied dependency on `curl`.

**Comment by andersfugmann** [comment]
You are right. The spec file (xml) should be added to git and have a target to update the spec which could be called manually to update. 

Ill create a patch, unless you beat me to it with a PR.

**Comment by Leonidas-from-XIV** [comment]
> Ill create a patch, unless you beat me to it with a PR.

I'll try to 🙂
