### ISSUE TITLE
New release on OPAM

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [andersfugmann/amqp-client#21]
Could you please make a new release and push it on OPAM? I assume the final release of OPAM 2.0 is not too far off (judging it is in release candidate state) so I assume many users upgrading from OPAM 1.x will run into the sandbox build issue, therefore it would be good if amqp-client would work OOTB. Thanks!

**Comment by andersfugmann** [comment]
https://github.com/ocaml/opam-repository/pull/12177

**Comment by andersfugmann** [comment]
New release 2.0.2 is now available in opam. 

Btw. I'm also using opam 2.0rc2, and the package 2.0.1 (which downloads the spec) works fine in sandbox mode (it uses bwrap to restrict system access), but it does not seem to restrict network access. How did you encounter the problem. Is it OSX specific maybe?

**Comment by Leonidas-from-XIV** [comment]
Thanks!

Yes, I have been running it on MacOS, where curl started failing it could not access www.rabbitmq.com. I first thought it was due to RabbitMQ being down, but a check in the browser worked, checking with curl worked too so I assumed it was due to the sandbox. I did not turn the sandbox off to check because it requires editing some shellscripts in `.opam` since there is no override switch.

**Comment by andersfugmann** [comment]
Its prob. a OSX thing then. 
Adding the spec to the repository also fixes some other problems. Also, the code makes assumptions over the spec, so as its coupled, there is no need to download it for every build.

Thanks for fixing it.
