### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by XVilka** [andersfugmann/amqp-client#24]
More complex example with multiple queues, exchanges and and interleaved publishing and consuming.

**Comment by andersfugmann** [comment]
Can you elaborate a bit on what your find confusing or difficult?
The library uses monadic style concurrency, so I assumed it was trivial to extrapolate how to declare multiple queues and consume / publish on these - But as the author, I'm possibly very biased. 

I would gladly accept PR's adding more "complex" examples.

**Comment by XVilka** [comment]
For example if I want to process two queues - one is "control" and second is "query" I need to do it in the loop, all the time calling `Query.consume ...; Query.cancel`, otherwise it catch only one message:
```ocaml
(* Consume all CONTROL packets *)
let control_queue_consumer ~(worker:Cluster.worker_record) channel queue =
    (* Lwt_io.printf "control_queue_consumer ()\n"; *)
    queue >>= fun q ->
    (* Here we consume only control messages *)
    let handler { Message.message = (_content, body); _ } =
        Lwt_io.printf "control queue msg handler\n";
        let (msgkind, protbuf) = decode_msg body in
        let result = match msgkind with
        | Register_cntl -> info_cntl_register protbuf
        | Deregister_cntl -> info_cntl_unregister protbuf
        | _ -> None
        in
        ()
    in
    Queue.consume ~no_ack:true
        ~id:worker.name channel q >>= fun (_consumer, reader) ->
    Pipe.iter_without_pushback reader ~f:(fun m -> handler m);
    Queue.cancel _consumer;
    return ()

(* Consume all QUERY packets *)
let query_queue_consumer ~(worker:Cluster.worker_record) channel queue =
    (* Lwt_io.printf "query_queue_consumer ()\n"; *)
    queue >>= fun q ->
    (* Here we consume only query messages *)
    let handler { Message.message = (_content, body); _ } =
        Lwt_io.printf "query queue msg handler\n";
        let (msgkind, protbuf) = decode_msg body in
        let result = match msgkind with
        | Query_notif -> info_query ~worker queue protbuf
        | Query_ack -> blacklist_query protbuf
        | Query_answer -> unblacklist_query protbuf
        | _ -> None
        in
        ()
    in
    Queue.consume ~no_ack:true
        ~id:worker.name channel q >>= fun (_consumer, reader) ->
    Pipe.iter_without_pushback reader ~f:(fun m -> handler m);
    Queue.cancel _consumer;
    return ()

let run_worker ~worker =
    Lwt_io.printf "Cluster monitor:\n";
    Lwt_io.printf "Starting listening threads...\n";
    channel >>= fun chan ->
    (* Create queue for handling queries *)
    Cluster.make_queue worker "query" |> fun query_queue ->
    (* Registering itself *)
    Lwt_io.printf "Registering worker...\n";
    Cluster.regsend worker;
    let rec loop () =
       (* Setting up the message handlers *)
        (* Control queue first *)
        control_queue_consumer ~worker chan control_queue >>= fun () ->
        (* Then queue for queries *)
        query_queue_consumer ~worker chan query_queue >>=
        loop
    in loop ()

let () =
    let id = Cluster.generate_identity () in
    let worker = Cluster.({
        id = id;
        version = worker_version;
        name = worker_name;
        typ = worker_type;
        category = worker_category;
    }) in
    Cluster.handle_signals worker;
    let server =
        Lwt.finalize (fun () ->
            run_worker ~worker >>= fun () -> raise Pervasives.Exit)
        (fun () ->
            prerr_endline "handled exception";
            Lwt.return ()) in
    Lwt_main.run server
```

But I find this solution ugly and most likely wrong. Is there any way to do the same without consuming and cancelling all the time?

**Comment by andersfugmann** [comment]
So you want to consume messages from each queue in order i.e. 
Process messages from queue A, then queue B, then A, then B and so on?

When consuming a queue, you get a pipe onto which all messages arrive.
So you get a Pipe back, from which you can read a single message (`Pipe.read`) or set it up to continuously process incoming messages (`Pipe.iter`).

So if you want to process them in order, then You can either setup a pipes as you do in the example but then control how you read from each. If you on the other hand just want to process the messages as they arrive on the queues as fast a possible, you can just iter over the two queues concurrently. 


```ocaml
let () = 
  let handler_a: Message.t -> unit Lwt.t  = ... in
  let handler_b: Message.t -> unit Lwt.t  = ... in
  Queue.declare ... >>= fun queue_a ->
  Queue.declare ... >>= fun queue_b ->
  Queue.consume ... queue_a >>= (consumer_a, reader_a) ->
  Queue.consume ... queue_b >>= (consumer_a, reader_b) ->

  let get_msg = function 
    | `Eof -> failwith "eof"
    | `Ok m -> m
  in

  (* Process in sequence in sequence *)
  let rec process_in_sequence () =  
    Pipe.read reader_a >>= fun msg ->
    handler_a (get_msg msg) >>= fun () ->
    Pipe.read reader_b >>= fun msg ->
    handler_a (get_msg msg) >>= fun () -> 
    process_in_sequence ()
  in

  let process_in_parallel () = 
    Lwt.pick [ 
        Pipe.iter_without_pushback reader_a ~f:handler_a;
        Pipe.iter_without_pushback reader_b ~f:handler_b;
    ]
  in

  (* Choose one of the two lines *)
  Lwt_result.catch process_in_sequence () >>= fun _whatever -> 
  Lwt_result.catch process_in_parallel () >>= fun _whatever -> 

  Queue.cancel consumer_a >>= fun () -> 
  Queue.cancel consumer_b >>= fun () -> 
  Lwt.return_unit
```
(Code in completely untested) 

Alternatively, you could also fetch one message at a time using Queue.get for the sequential version. 

Please pay special attention when consuming messages in no_ack mode. You queues might fill up on the receiver end. 

It occurs to me that this is more a question on how to write concurrent programs in ocaml using Lwt, rather than a specific question on how to use this library. Would that be a fair assessment? If you I would really recommend reading https://realworldocaml.org/. It uses Core Async, but it does explain the fundamentals about the concurrency monad.

**Comment by XVilka** [comment]
@andersfugmann thank you for so detailed answer, seems exactly what I need! I will check tomorrow.

P.S. No, I know about Lwt and concurrent programming, it wasn't just clear how exactly to combine those consumers/producers within standard Lwt patterns.

**Comment by XVilka** [comment]
Also I think this will make a good example in the repo.

**Comment by andersfugmann** [comment]
Ive added the example to the repo.
