### ISSUE TITLE
Add URL parsing feature

### ISSUE THREAD

**Issue by XVilka** [andersfugmann/amqp-client#25]
Like in Python's pika with its `pika.URLParameters("ampq://user:password@hostname:port/vhost?params")`

**Comment by andersfugmann** [comment]
I'm curious to understand why and how you would use such a feature?

**Comment by XVilka** [comment]
Ah, it is useful to keep this line in the config, instead of separate parameters, so both pika Python nodes and OCaml nodes (I use both as part of the same system) can read this.

**Comment by andersfugmann** [comment]
How should the params part be interpreted?

**Comment by XVilka** [comment]
See https://pika.readthedocs.io/en/0.10.0/modules/parameters.html#pika.connection.URLParameters

**Comment by XVilka** [comment]
But I think those parameters are not so important after all. Everything else - is, especially using SSL in case of `ampqs://`

**Comment by andersfugmann** [comment]
Currently the amqp-client does not support ssl - It might in the future, but I have no concrete plans to implement it though I don't think it requires that much work.

**Comment by XVilka** [comment]
Thanks a lot!
