### ISSUE TITLE
Adding basic example with LWT

### ISSUE THREAD

**Issue by flefevre** [andersfugmann/amqp-client#29]
Nice project!
I would like to know if you plan to add a basic example with LWT library as you did with Amqp_client_async.
Moreover for newbbies in ocaml, could you add in the example readme, the way to compile and run your examples, see https://github.com/andersfugmann/amqp-client/tree/master/examples
Thanks a lot

**Comment by andersfugmann** [comment]
I've updated the readme to include an lwt version of the small example (including build instructions). I've also noted how to build the examples and a reference to dune, as I would recommend dune for all ocaml projects.

**Comment by andersfugmann** [comment]
Thanks for your comments.
