### ISSUE TITLE
Unexpected routing key assignment

### ISSUE THREAD

**Issue by martinslota** [andersfugmann/amqp-client#32]
It seems that when several queues are being declared and bound concurrently, the routing keys (usually?) end up assigned in a very unexpected way. Here's a branch with an example binary:

https://github.com/martinslota/amqp-client/tree/routing-key-mayhem

It can be run as follows:

`AMQP_HOST=<HOSTNAME> dune exec routing_key_mayhem/unleash.exe`

While the binary is running, you can take a look at the bound queues:

<img width="823" alt="Screenshot 2019-07-22 at 22 47 01" src="https://user-images.githubusercontent.com/46676886/61664237-a9007580-acd2-11e9-8b07-bac690857497.png">

The queues ending with `endpoint1` and `endpoint2` will (probably?) have swapped routing keys:

<img width="778" alt="Screenshot 2019-07-22 at 22 49 02" src="https://user-images.githubusercontent.com/46676886/61664489-25935400-acd3-11e9-8244-6869c0afe6c9.png">

That's the unexpected part.

Note also that queues ending with `endpoint3` and `endpoint4` which were declared and bound sequentially have the routing keys assigned as expected.

**Comment by andersfugmann** [comment]
New opam release 2.2.0 pending: https://github.com/ocaml/opam-repository/pull/14571
