### ISSUE TITLE
Autogenerated queue names.

### ISSUE THREAD

**Issue by NightBlues** [andersfugmann/amqp-client#38]
I'm going through rabbitmq tutorials with this lib and in the 3rd tutorial (https://www.rabbitmq.com/tutorials/tutorial-three-python.html) they advice to autogenerate queue names on server:
```
Firstly, whenever we connect to Rabbit we need a fresh, empty queue. To do it we could create a queue with a random name, or, even better - let the server choose a random queue name for us. We can do this by supplying empty queue parameter to queue_declare:

result = channel.queue_declare(queue='')

At this point result.method.queue contains a random queue name. For example it may look like amq.gen-JzTY20BRgKO-HjmUJj0wLg.
```
It actually works fine with commenting-out this line:
https://github.com/andersfugmann/amqp-client/blob/master/async/src/queue.ml#L21

so I get in my debug prints:
```
consumer A queue name is amq.gen-WdhDKuvRzle__VOXGm2mvg
consumer B queue name is amq.gen-V7mTAhFOdjP9rroOSVSN8g
```
Also assertion doesn't look intuitive
```
Fatal error: exception File "amqp-client/async/src/queue.ml", line 21, characters 2-8: Assertion failed
Raised at file "src/core/lwt.ml", line 2998, characters 20-29
Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
Called from file "rabbit/test/test2.ml", line 57, characters 2-157
```
May be replace this assertion with check if its an empty string or not and add friendly message? I can do a PR if you confirm this changes.

**Comment by andersfugmann** [comment]
A PR to make the exception raised a bit friendlier looking would be nice indeed.

Wrt. auto-generated queue names, I really would discourage it, and I think its a mistake in the AMQP spec to require it. In production we have had thousands of these queue floating around, and its virtually impossible to find out which services are leaking these queues. 

I could also accept PR to add a special optional flag `.. -> autogenerate:bool -> ...` - and add documentation comment on why this is discouraged. (This would of course also require that the queue name is the empty string.

**Comment by NightBlues** [comment]
Well, I don't really need this feature (at least yet) - I'm just walking through tutorial. I think that impossibility to use auto-generated at server random name can not stop people from doing the same at client side. Also I don't know if its a feature of amqp, or just rabbitmq hack.

**Comment by andersfugmann** [comment]
Its actually mandated by the spec: https://www.rabbitmq.com/amqp-0-9-1-reference.html#queue.declare
