### ISSUE TITLE
Fails with empty string queue name

### ISSUE THREAD

**Issue by phiSgr** [andersfugmann/amqp-client#4]
If I’m not mistaken, RabbitMQ generates a random queue name if the queue name supplied is an empty string. Then `assert (rep.Declare_ok.queue = name)` on line 23 in `amqp_queue.ml` will fail.

**Comment by andersfugmann** [comment]
True, bit Its a pattern that should be avoided as its very hard to debug. 

The function should be extended to create a unique name at client side that will allow traceability when given the empty string. Ill fix this in the next release.

**Comment by andersfugmann** [comment]
Well. For now Ill just use the name given from the amqp-server. Its a broken pattern IMHO but for now its allowed.
